version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=flappy_rewards
      - JWT_SECRET=your_super_secret_key
    depends_on:
      - mongo
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          # ignore:
          #   - node_modules/
        - action: rebuild
          path: package.json

  mongo:
    image: mongo:6
    restart: always
    container_name: flappy_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
